blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/n6ai/minze/discussions
    about: Ask questions and discuss with others on GitHub discussions.
